---
# tasks file for borg_backup

- name: copy borg scripts to {{ borg_bin_dir }} target machine
  template:
    src: '{{ role_path }}/templates/{{ item.script }}.sh.j2'
    dest: '{{ borg_bin_dir }}/{{ item.script }}-{{ borg_backup_name }}.sh'
    mode: '{{ item.mode }}'
  loop:
    - script: borg-create
      mode: '740'
    - script: borg-info
      mode: '740'
    - script: borg-list
      mode: '740'
    - script: borg-mount
      mode: '740'
    - script: borg-umount
      mode: '740'
    - script: borg-delete
      mode: '640'
    - script: borg-init
      mode: '640'

- name: add borg-create.sh to crontab
  cron:
    name: '{{ role_name }}_{{ borg_backup_name }}'
    job: '{{ borg_bin_dir }}/borg-create-{{ borg_backup_name }}.sh >> {{ borg_create_log_file }} 2>&1'
    user: '{{ borg_user_id }}'
    hour: '{{ borg_backup_create_hour }}'
    minute: '{{ borg_backup_create_minute }}'
