---
# tasks file for mirror_share

- name: Create directory structure
  become: true
  loop:
    - '{{ mirror_share_bin_directory }}'
    - '{{ mirror_share_mountpoint }}'
    - '{{ mirror_share_log_directory }}'
    - '{{ mirror_share_destination }}'
    - '{{ mirror_share_lib_directory }}'
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ mirror_share_user_id }}'
    group: '{{ mirror_share_group_id }}'

- name: Create {{ mirror_share_credentials_file }}
  copy:
    dest: '{{ mirror_share_credentials_file }}'
    content: '{{ mirror_share_credentials }}'
    mode: 0400

- name: copy mirror-share-if-available.sh to {{ mirror_share_bin_directory }}
  template:
    src: '{{ role_path }}/templates/mirror-share-if-available.sh.j2'
    dest: '{{ mirror_share_bin_directory }}/mirror-share-if-available.sh'
    mode: '740'

- name: integrate logrotate block into logrotate configuration
  become: true
  blockinfile:
    path: '{{ mirror_share_logrotate_file }}'
    block: "{{ lookup('template', role_path + '/templates/logrotate') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ role_name }}"
    create: true

- name: add mirror-share-if-available.sh to crontab
  cron:
    name: '{{ role_name }}'
    job: '{{ mirror_share_bin_directory }}/mirror-share-if-available.sh >> {{ mirror_share_log_file }} 2>&1'
    user: '{{ mirror_share_user_id }}'
