---

- name: install borg backup scripts for backup local
  hosts: localhost
  roles:
    - role: roles/borg_backup
  vars:
    borg_bin_dir: ~/bin
    borg_backup_name: local
    borg_source_directory: /srv/dev-disk-by-label-data/spiegel
    borg_repository: /srv/dev-disk-by-label-data/backup
    borg_passcommand: "cat ${HOME}/.borg-passphrase-local"
    borg_mountpoint: /srv/dev-disk-by-label-data/restore/local
    borg_archive_prefix: julian-
    borg_alert_command: /srv/dev-disk-by-label-data/home/julian/bin/nextcloud-talk-alert.sh
    borg_keep:
      daily: 7
      weekly: 2
      monthly: 2

- name: install borg backup scripts for backup offshore
  hosts: localhost
  roles:
    - role: roles/borg_backup
  vars:
    borg_bin_dir: ~/bin
    borg_backup_name: offshore
    borg_source_directory: /srv/dev-disk-by-label-data/spiegel
    borg_repository: /srv/43010960-b7dc-40e0-9edc-9cb94c483ade/Elements/backup
    borg_passcommand: "cat ${HOME}/.borg-passphrase-offshore"
    borg_mountpoint: /srv/dev-disk-by-label-data/restore/offshore
    borg_archive_prefix: julian-
    borg_alert_command: /srv/dev-disk-by-label-data/home/julian/bin/nextcloud-talk-alert.sh
    borg_keep:
      daily: 0
      weekly: 2
      monthly: 0
