---

- name: install borg backup scripts for backup local
  hosts: raspberrypi
  roles:
    - role: borg_backup
  vars:
    borg_version: 1.1.15-3~bpo10+1
    borg_home: /srv/dev-disk-by-label-data/home/julian
    borg_bin_dir: '{{ borg_home }}/bin'
    borg_backup_name: local
    borg_source_directory: /srv/dev-disk-by-label-data/spiegel
    borg_repository: /srv/dev-disk-by-label-data/backup
    borg_passcommand: "cat ${HOME}/.borg-passphrase-local"
    borg_mountpoint: /srv/dev-disk-by-label-data/restore/local
    borg_archive_prefix: julian-
    borg_alert_command: '{{ borg_home }}/bin/nextcloud-talk-alert.sh'
    borg_keep:
      daily: 7
      weekly: 2
      monthly: 2
    borg_create_log_file: '{{ borg_home }}/var/log/borg/borg-create-{{ borg_backup_name }}.log'
    borg_create_logrotate_file: /etc/logrotate.d/julian
    borg_user_id: julian
    borg_group_id: julian
    borg_backup_create_hour: 3
    borg_backup_create_minute: 0

- name: install borg backup scripts for backup offshore
  hosts: raspberrypi
  roles:
    - role: borg_backup
  vars:
    borg_version: 1.1.15-3~bpo10+1
    borg_home: /srv/dev-disk-by-label-data/home/julian
    borg_bin_dir: '{{ borg_home }}/bin'
    borg_backup_name: offshore
    borg_source_directory: /srv/dev-disk-by-label-data/spiegel
    borg_repository: /srv/43010960-b7dc-40e0-9edc-9cb94c483ade/Elements/backup
    borg_passcommand: "cat ${HOME}/.borg-passphrase-offshore"
    borg_mountpoint: /srv/dev-disk-by-label-data/restore/offshore
    borg_archive_prefix: julian-
    borg_alert_command: '{{ borg_home }}/bin/nextcloud-talk-alert.sh'
    borg_keep:
      daily: 0
      weekly: 2
      monthly: 0
    borg_create_log_file: '{{ borg_home }}/var/log/borg/borg-create-{{ borg_backup_name }}.log'
    borg_create_logrotate_file: /etc/logrotate.d/julian
    borg_user_id: julian
    borg_group_id: julian
    borg_backup_create_hour: 4
    borg_backup_create_minute: 0
