---

- name: install borg backup scripts for local backup
  hosts: localhost
  roles:
    - role: roles/borg_backup
  vars:
    borg_bin_dir: ~/bin
    borg_backup_name: local
    borg_source_directory: /srv/dev-disk-by-label-data/spiegel
    borg_repository: /srv/dev-disk-by-label-data/backup
    borg_passcommand: "cat ${HOME}/.borg-passphrase-local"
    borg_mountpoint: /srv/dev-disk-by-label-data/restore/local
    borg_archive_prefix: julian-
    borg_alert_command: /srv/dev-disk-by-label-data/home/julian/bin/nextcloud-talk-alert.sh
    borg_keep:
      daily: 7
      weekly: 2
      monthly: 2
