---

- name: Basic provisioning
  hosts: raspberrypi
  vars:
    user: julian
    group: julian
    samba_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30336462633737623438666263613733633765393461363834666134643865353666343465616531
      3539363665623337653131383338623331663334346561610a363034626461393063343163383133
      64643265626430386332336461356166313761313332343333653665366265346231343138383139
      3331616437363161310a313837663263303765373732333463306466643331613761306465396562
      3638
    remote_share_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34373363383231623761303062653730653438366564396439323131366262303961336330383466
      6161333764313937646663613539343838653630613962650a643636333766386533353164616132
      30666161343864376562626363396434316530636239396230373539303564636331316238666431
      3733316538336264610a323830666139383034616662656130373361393830666537623339346466
      33646134313539316234353038633064376265373432626432313433653232386633
  tasks:
    - name: ping
      ping:
      tags: dry-run

    - name: apt update
      become: true
      apt:
        update_cache: true

    - name: apt upgrade
      become: true
      apt:
        upgrade: true

    - name: mount external drive
      become: true
      mount:
        src: /dev/sda1
        path: /srv/dev-disk-by-label-data
        state: mounted
        boot: true
        fstype: ext4

    - name: set standard editor to vim
      become: true
      lineinfile:
        path: /etc/environment
        state: present
        create: true
        line: "{{ item }}"
      loop:
        - 'EDITOR=/usr/bin/vim'
        - 'VISUAL=/usr/bin/vim'

    - name: Allow the user to run sudo without a password
      become: true
      copy:
        dest: /etc/sudoers.d/{{ ansible_user }}
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'

    - name: install cifs-utils
      become: true
      package:
        name: cifs-utils
        state: present

    - name: install samba
      become: true
      package:
        name: samba
        state: present

    - name: Add samba shares
      become: true
      blockinfile:
        path: /etc/samba/smb.conf
        state: present
        marker_begin: BEGIN {{ item }}
        marker_end: END {{ item }}
        block: |
          [{{ item }}]
          path = /srv/dev-disk-by-label-data/{{ item }}
          browseable = yes
          writable = yes
          valid users = @sambashare
          create mask = 0775
          directory mask = 0775
      loop:
        - backup
        - home
        - restore
        - spiegel

    - name: Restart Samba service to apply changes
      become: true
      service:
        name: smbd
        state: restarted
        enabled: true

    - name: Add {{ user }} to group sambashare
      become: true
      user:
        name: '{{ user }}'
        groups: sambashare
        append: true
    
    - name: Remove samba user {{ user }}
      become: true
      shell: smbpasswd -x {{ user }}
      register: result
      failed_when: result.rc not in [0, 1]

    - name: Set the samba password for {{ user }}
      become: true
      expect:
        command: smbpasswd -a {{ user }}
        responses:
          'New SMB password:': "{{ samba_password }}"
          'Retype new SMB password:': "{{ samba_password }}"

    - name: Enable the Samba user {{ user }}
      become: yes
      command: smbpasswd -e {{ user }}

    - name: Create /srv/43010960-b7dc-40e0-9edc-9cb94c483ade
      become: true
      file:
        path: /srv/43010960-b7dc-40e0-9edc-9cb94c483ade
        state: directory
        mode: '0755'
        owner: '{{ user }}'
        group: '{{ group }}'

    - name: Create credentialsfile
      copy:
        dest: /home/julian/.cifscredentials-remote
        content: |
          username={{ user }}
          password={{ remote_share_password }}
        owner: '{{ user }}'
        group: '{{ group }}'
        mode: '0400'

    - name: Mount remote share
      become: true
      mount:
        src: //192.168.178.1/home
        path: /srv/43010960-b7dc-40e0-9edc-9cb94c483ade
        fstype: cifs
        opts: _netdev,iocharset=utf8,vers=3.0,nofail,uid=julian,gid=julian,file_mode=0770,dir_mode=0770,noserverino,credentials=/home/julian/.cifscredentials-remote
        state: mounted
        boot: true
