---

- name: Basic provisioning
  hosts: raspberrypi
  tasks:
    - name: ping
      ping:
      tags: dry-run

    - name: apt update
      become: true
      apt:
        update_cache: true

    - name: apt upgrade
      become: true
      apt:
        upgrade: true
