---

- name: Install yt-dlp
  hosts: raspberrypi
  tasks:
    - name: Add repo ppa:tomtomtom/yt-dlp
      become: true
      apt_repository:
        repo: ppa:tomtomtom/yt-dlp
        state: present

    - name: apt update
      become: true
      apt:
        update_cache: true

    - name: Install or upgrade yt-dlp
      become: true
      apt:
        name: yt-dlp
        state: latest
        update_cache: true
