---

- name: Install yt-dlp
  hosts: raspberrypi
  become: true

  tasks:

    - name: Download latest yt-dlp
      ansible.builtin.get_url:
        url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
        dest: /usr/local/bin/yt-dlp
        mode: '0755'
        force: true

    - name: Check yt-dlp version
      ansible.builtin.command:
        cmd: /usr/local/bin/yt-dlp --version
      register: yt_dlp_version
      changed_when: false

    - name: Display yt-dlp version
      ansible.builtin.debug:
        msg: "Installed yt-dlp version: {{ yt_dlp_version.stdout }}"
